config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :scripts

  root to: "scripts#index"

  devise_for :user

  get 'scripts/:id/export.ics' => 'scripts#export', as: :ics_export
  get 'scripts/:id/pdf.pdf' => 'scripts#pdf'

end

app/models/script.rb
# == Schema Information
#
# Table name: scripts
#
#  id         :integer          not null, primary key
#  script     :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#  slug       :string
#

class Script < ActiveRecord::Base
  extend FriendlyId
  friendly_id :user_username, use: [:slugged, :finders]

  validates :user, presence: true, uniqueness: true
  validates :script, presence: true

  attr_accessor :semester_start, :semester_end

  belongs_to :user

  def user_username
    self.user.username
  end

  ###################################################
  ## Parse the script and return an array of Course objects
  ## Input : Timetable text
  ## Output : Array containing Course objects
  ###################################################
  def parse
    begin
      script = self.script

      result = Array.new
      lines = Array.new

      script.split("\n").each do |line|
        # / is for classes that have two schedules
        # MT90 for example due to the high number of participants have two classes
        # The two classes are separated by a /
        # We only pick the first one
        l = line.split('/').first.nil? ? nil : line.split('/').first.split(' ')
        lines.push(l) unless l.nil? || l.count == 0
      end

      # Get rid of the first line : "---...---" (dashes) if it's present
      if lines[0][0].chars.to_a.uniq.count < 3
        lines.delete_at(0)
      end

      # Get rid of the second line : "login semester numberOfCourses course1 course2 ..." if it's present
      if lines[0][0].length == 8
        lines.delete_at(0)
      end

      # Get rid of the last line : "LE SERVICE des MOYENS d'ENSEIGNEMENT VOUS SOUHAITE BON COURAGE"
      if lines.last.include?("SERVICE") || lines.last.include?("ENSEIGNEMENT") || lines.last.include?("COURAGE")
        lines.delete_at(lines.size - 1)
      end


      # lines[0..-1] should contain courses info
      lines[0..-1].each do |l|
        result.push(Course.new l)
      end

      result
    rescue => e
      raise if Rails.env.development?
      "Can't do it, sorry :(. Please check that you have correctly copied your timetable."
    end
  end

  ###################################################
  ## Interpret the input
  ## Input : Timetable text
  ## Output : Ical file
  ###################################################
  def semester_start
    @semester_start ||= DateTime.new(2015, 9, 1)
  end

  def semester_end
    @semester_end ||= DateTime.new(2016, 1, 8)
  end

  def holiday_all
    Rails.cache.fetch("holiday_all", expires_in: 1.day) do
      Holiday.all
    end
  end

  def invalid_date(date)
    invalid = false

    holiday_all.all.each do |h|
      invalid = invalid || h.get_range.cover?(date)
    end

    invalid
  end

  def to_ical
    parsed_script = self.parse

    cal = Icalendar::Calendar.new

    parsed_class = parsed_script.first
    parsed_script.each do |parsed_class|
      (semester_start..semester_end).step(7) do |d|
        st_date = (d.monday+parsed_class.day).change(hour: parsed_class.st_hour[0..1].to_i, min: parsed_class.st_hour[3..4].to_i)
        end_date = (d.monday+parsed_class.day).change(hour: parsed_class.end_hour[0..1].to_i, min: parsed_class.end_hour[3..4].to_i)
        unless invalid_date(st_date)
          cal.event do |e|
            # st_hour and end_hour format : "HH:mm"
            e.dtstart = st_date
            e.dtend = end_date
            e.summary = parsed_class.course + " - " + parsed_class.type
            e.location = parsed_class.classroom
            e.ip_class = "PRIVATE"
          end
        end
      end
    end
    Holiday.all.each do |h|
      cal.event do |e|
        e.dtstart = h.begin_at
        e.dtstart.ical_params = { "VALUE" => "DATE" }
        e.dtend = h.end_at
        e.dtend.ical_params = { "VALUE" => "DATE" }
        e.summary = h.name
        e.ip_class = "PRIVATE"
      end
    end

    cal
  end

  def write_cal(cal)
    File.open('./test.ics', 'w') { |file| file.write(cal.to_ical) }
  end

end

app/controllers/scripts_controller.rb
# Testing
# rails console
# controller = ScriptsController.new
# parsed_script = controller.parse_script(Script.last.script)
# cal = controller.interpret_parsed_script(parsed_script)

class ScriptsController < ApplicationController
  before_action :set_script, only: [:show, :edit, :update, :destroy, :export, :pdf]
  require 'icalendar'

  def index
    @script = current_user.script
    if @script
      redirect_to script_url(@script)
    else
      redirect_to new_script_url
    end
  end

  # GET /scripts/1
  # GET /scripts/1.json
  def show
    begin
      @parsed_script = @script.parse

      # Sort @parsed_script with day and st_hour
      @parsed_script.sort! do |x, y|
        comparison = x.day <=> y.day
        comparison.zero? ? (x.st_hour <=> y.end_hour) : comparison
      end

      # construct array of courses
      @courses = Array.new(@parsed_script.length)
      @parsed_script.each do |p|
        @courses.push(p.course) unless p.course.in?(@courses)
      end

      # construct courses_events json object for fullcalendar
      @courses_events = Array.new(@parsed_script.length) { Hash.new }
      i = 0
      @parsed_script.each do |p|
        @courses_events[i]["title"] = p.course + " - " + p.type
        tempday = Date.today.monday.to_datetime + p.day
        @courses_events[i]["start"] = tempday.change(hour: p.st_hour[0..1].to_i, min: p.st_hour[3..4].to_i).to_s
        @courses_events[i]["end"] = tempday.change(hour: p.end_hour[0..1].to_i, min: p.end_hour[3..4].to_i).to_s
        i += 1
      end
      @courses_events = @courses_events.to_json.html_safe

      @semester_start_date = @script.semester_start.to_date
      @semester_end_date = @script.semester_end.to_date
    rescue => e
      raise e if Rails.env.development?
      @script.destroy unless @script.nil?
      redirect_to new_script_path, flash: {error: e.message}
    end
  end

  # GET /scripts/new
  def new
    @script = Script.new
  end

  # GET /scripts/1/edit
  def edit
  end

  # POST /scripts
  # POST /scripts.json
  def create
    old_script = current_user.script
    if old_script
      old_script.destroy
    end

    @script = Script.new(script_params)
    @script.user = current_user

    respond_to do |format|
      if @script.save
        format.html { redirect_to @script, notice: 'Script was successfully created.' }
        format.json { render :show, status: :created, location: @script }
      else
        format.html { render :new }
        format.json { render json: @script.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scripts/1
  def update
    respond_to do |format|
      if @script.update(script_params)
        format.html { redirect_to @script, notice: 'Script was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /scripts/1
  # DELETE /scripts/1.json
  def destroy
    @script.destroy
    respond_to do |format|
      format.html { redirect_to scripts_url, notice: 'Script was successfully destroyed.' }
    end
  end

  def export
    begin
      if params[:semester_start_date].present? && params[:semester_end_date]
        @script.semester_start = params[:semester_start_date].to_date.to_datetime
        @script.semester_end = (params[:semester_end_date].to_date + 1.day).to_datetime
      end
      cal = @script.to_ical
      cal.publish
      render inline: cal.to_ical, content_type: 'text/calendar'
    rescue => e
      raise e if Rails.env.development?
      render inline: "Woops, that didn't quite work !"
    end
  end

  def pdf
   @parsed_script = @script.parse

      # construct array of courses
      @courses = Array.new(@parsed_script.length)
      @parsed_script.each do |p|
        @courses.push(p.course) unless p.course.in?(@courses)
      end

    @parsed_script.each do |p|
      p.day = p.day == 3 ? 'Th' : Date::DAYNAMES[(p.day+1)%7][0]
    end
    render 'scripts/pdf.pdf.rtex' 
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_script
    @script = current_user.script
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def script_params
    params.require(:script).permit(:script)
  end

end

app/views/scripts/_form.html.erb
<%= form_for(@script) do |f| %>
  <% if @script.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@script.errors.count, "error") %> prohibited this script from being saved:</h2>

      <ul>
      <% @script.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label 'Timetable' %><br>
    <%= f.text_area :script, class: 'form-control', style: 'height: 500px;' %>
  </div>
  <div class="actions">
    <%= f.submit 'Submit', class: 'btn btn-default' %>
  </div>
<% end %>

app/views/scripts/edit.html.erb
<h1>Editing your timetable</h1>

<div class="text-center">
  <div class="btn btn-info">
    <%= link_to "Get my timetable (experimental)", "http://wwwetu.utc.fr/sme/EDT/#{current_user.username}.edt", target: '_blank' %>
  </div>
</div>

<%= render 'form' %>

<%= link_to 'Show', @script %> |
<%= link_to 'Back', scripts_path %>

app/views/scripts/new.html.erb
<h1>Insert your timetable</h1>

<div class="text-center">
  <div class="btn btn-info">
    <%= link_to "Get my timetable (experimental)", "http://wwwetu.utc.fr/sme/EDT/#{current_user.username}.edt", target: '_blank' %>
  </div>
</div>

<%= render 'form' %>

app/views/scripts/show.html.erb
<%= javascript_include_tag params[:controller] %>
<script>
    courses = <%= @courses.to_json.html_safe %>;
    courses_events = <%= @courses_events %>;
</script>

<div class="row">
  <div class="text-center">
    <%= link_to 'Edit', edit_script_path(@script), class: 'btn btn-default' %>
    <%= link_to 'Erase everything !', @script, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default' %>
  </div>
</div>
<hr/>
<div class="row">
  <div class="text-center">
    <h1><%= fa_icon "database" %> Data <%= fa_icon "database" %></h1>
  </div>
  <div class="col-md-5">
    <pre>
      <%= @script.script %>
    </pre>
  </div>

  <div class="col-md-2 text-center">
    <%= fa_icon 'arrow-right', class: 'fa-5x' %>
  </div>

  <div class="col-md-5">
    <% if @parsed_script.is_a?(String) %>
        <%= @parsed_script %>
    <% else %>

        <table class="table table-responsive">
          <thead>
          <th>Course</th>
          <th>Type</th>
          <th>Semaine</th>
          <th>Day</th>
          <th>Start hour</th>
          <th>End hour</th>
          <th>Frequency</th>
          <th>Classroom</th>
          </thead>
          <tbody>
          <% @parsed_script.each do |p| %>
              <tr>
                <td><%= p.course %></td>
                <td><%= p.type %></td>
                <td><%= p.week %></td>
                <td><%= Date::DAYNAMES[(p.day+1)%7] %></td>
                <td><%= p.st_hour %></td>
                <td><%= p.end_hour %></td>
                <td><%= p.frequency %></td>
                <td><%= p.classroom %></td>
              </tr>
          <% end %>
          </tbody>

        </table>

    <% end %>
  </div>
</div>

<hr/>

<div class="row text-center">
  <%= fa_icon 'arrow-down', class: 'fa-5x' %>
</div>
<div class="text-center">
  <h1><%= fa_icon "table" %> Timetable <%= fa_icon "table" %></h1>
</div>

<div class="row">
  <div class="col-md-10 col-md-offset-1 col-sm-12 col-lg-8 col-lg-offset-2">
    <div class="text-center">
      <div id="pdfv2button" class="btn btn-default">
        <span id="calendar_btn_pdf_2" class=""><%= link_to 'To PDF v2', { action: 'pdf' }, { style: 'color: black;' } %></span>
      </div>
    </div><br>
    <div>
      <h2>ICS export</h2>
      <div>
        <%= form_tag ics_export_path, method: :get do %>
          <%= label_tag :semester_start_date %>
          <%= text_field_tag :semester_start_date, @semester_start_date, class: 'form-control datepicker' %>
          <%= label_tag :semester_end_date %>
          <%= text_field_tag :semester_end_date, @semester_end_date, class: 'form-control datepicker' %>
          <%= submit_tag 'Export ICS', class: 'btn btn-default' %>
        <% end %>
      </div>
    </div>
    <div>
      <h2>Graphic export</h2>
    </div>
    <div class="text-center">
      <div id="pngbutton" class="btn btn-default">
        <span id="calendar_btn_png" class=""><input type="hidden" id="zz_png" value="" />To PNG</span>
      </div>
      <div id="pdfbutton" class="btn btn-default">
        <span id="calendar_btn_pdf" class=""><input type="hidden" id="zz_pdf" value="" />To PDF</span>
      </div>
    </div>
    <div class="form-group form-inline clearfix">
      <div class="pull-left">
        <input id="selected_color" class="form-control" style="width: 150px"></input>
      </div>
      <span class="alert alert-info pull-right"><%= fa_icon 'info-circle' %> Select a color on the left and click on an event to change its colors</span>
    </div>
    <div id='calendar-container'>
      <div id='calendar' style="width: 100%;  background-color: #ffffff; border: 1px solid black;"></div>
    </div>
  </div>
</div>